### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by DJViking** [jfree/jfreechart-fx#1]
TimeSeriesChartFXDemo1.java:[103,21] cannot find symbol
  symbol:   method setBaseShapesVisible(boolean)
  location: variable renderer of type org.jfree.chart.renderer.xy.XYLineAndShapeRenderer
TimeSeriesChartFXDemo1.java:[107,21] cannot find symbol
  symbol:   method setBaseStroke(java.awt.BasicStroke,boolean)
  location: variable renderer of type org.jfree.chart.renderer.xy.XYLineAndShapeRenderer

I built the latest jfreechart prior to this.

**Comment by jfree** [comment]
Oops...fixed that.  Thanks for reporting it.
