### ISSUE TITLE
False file extention formats for FileChooser in ChartViewer.class

### ISSUE THREAD

**Issue by amassalimov** [jfree/jfreechart-fx#7]
When you save an image you need to type file.png in as a file name (not just file)
I guess it should be not "png" but "*.png" etc.  

wrong: new FileChooser.ExtensionFilter(
                "Portable Document Format (PDF)", "pdf");

right?: new FileChooser.ExtensionFilter(
                "Portable Document Format (PDF)", "*.pdf");

**Comment by jfree** [comment]
Thanks for the report, I committed a fix for this for the next release.
